# creation rules are evaluated sequentially, the first match wins
creation_rules:
  # upon creation of a file that matches the pattern *dev.yaml,
  # KMS set A is used
  # eGOV Internal ------------------------------------------------------------------------------------------------------------- #
  - path_regex: environments/azure-nigeria-uat-secrets.yaml$
    azure_keyvault: "https://ng-uat.vault.azure.net/keys/ng-uat/145aa46063044683bde02cf70ab6338e"